version: '3.1'

services:
  application:
    build:
      context: '/home/matheus/www/model_api'
      dockerfile: '/home/matheus/www/model_api/Dockerfile'
    container_name: application
    ports:
      - 3333:3333
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - metrics

  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    # hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - metrics

networks:
  metrics:
    driver: bridge