global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # http://host.docker.internal:9090
  
  - job_name: "example-nodejs-app"
    static_configs:
      - targets: ["application:3333"]